#HelloWorld.py" file in c:\dev\python with this as the content:
#print('Content-Type: text/plain')
#print('')
#print('Hello, world!')

print('Content-Type: text/html')
print('<!DOCTYPE html>')
print('<html>')
print('<head>')
print('<title>Index</title>')
print('<body>')
print('<h1>Card Game</h1>')
print('<p>Playing five cards.</p>')
print('<a href="CardGame.html">Card game</a></head>')
print('</html>')
